language: node_js
sudo: false
node_js:
  - "8"
  - "10"
  - "node"

jobs:
  include:
    - stage: release
      node_js: "10"
      deploy:
        provider: "script"
        skip_cleanup: true
        script:
          - "npx semantic-release"
