language: node_js
sudo: false
node_js:
  - "8"
  - "10"
  - "12"
  - "node"

install:
  - "npm install --ignore-scripts"
  - "node bin/allow-scripts.js"

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: "10"
      deploy:
        provider: "script"
        skip_cleanup: true
        script:
          - "npx semantic-release"
